[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = ["ds-test/=lib/ds-test/src/", "solmate/=lib/solmate/src/", "forge-std/=lib/forge-std/src/", "base64-sol/=lib/base64/", "@openzeppelin/=lib/openzeppelin-contracts/"]
verbosity = 3