on: push

name: Unit Tests

defaults:
  run:
    shell: bash

env:
  CI: true
  FORCE_COLOR: 2

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Forge
        id: cache-forge
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/forge
          key: cache-forge

      # if couldn't get, install it
      - name: Install Forge
        if: steps.cache-forge.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/gakonst/foundry --bin forge --locked

      - name: Run tests
        run: forge test --verbosity 3
